name: Deploy Docker Application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS 

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar o AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Instalar o SSH Client
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 4. Copiar arquivos para o EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 ec2-user@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            REPO_DIR="/home/ec2-user/tech-challenge-02" # Diretório do repositório

            cd $REPO_DIR

            git pull origin main

            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start

            sudo docker system prune -f
            docker-compose down || true
            docker-compose up -d --build
          EOF
