name: Build and Deploy Monorepo

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração de credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Altere para a região correta

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build da aplicação completa usando Docker Compose
      - name: Build application using Docker Compose
        run: docker-compose build

      # Construir e copiar os microfrontends para o S3
      - name: Build and deploy Microfrontend: Host
        run: |
          docker-compose up -d host
          aws s3 sync ./frontend/host/dist s3://your-bucket-host --delete

      - name: Build and deploy Microfrontend: Dashboard
        run: |
          docker-compose up -d dashboard
          aws s3 sync ./frontend/dashboard/dist s3://your-bucket-dashboard --delete

      # (Opcional) Invalidação do CloudFront (para cache global, se necessário)
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
